import{i as c,S as d}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const f=document.querySelector("input");f.value.trim();function p(o){const i=`https://pixabay.com/api/?${new URLSearchParams({key:"43050559-0509edef54e5bc117deb7e6a8",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(i).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}const h=document.querySelector(".gallery");function g(o){if(o.length==0)c.error({message:"Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const s=o.map(r=>`<li class="photo-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img class="photo" src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="container">
        <li class="item-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");h.insertAdjacentHTML("beforeend",s),new d(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}}const y=document.querySelector(".gallery");let n=L.value.trim();const L=document.querySelector("input"),l=document.querySelector("form"),u=document.querySelector(".loader");m();function b(){u.classList.remove("hidden")}function m(){u.classList.add("hidden")}l.addEventListener("submit",o=>{o.preventDefault(),b(),y.innerHTML="",n===""&&c.error({color:"red",message:" Please fill in the field for search",position:"topRight"}),n&&p(n).then(s=>g(s.hits)).catch(s=>{c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}).finally(()=>m()),l.reset()});
//# sourceMappingURL=commonHelpers.js.map
