import{i as c,S as p}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const f=document.querySelector("input");f.value.trim();function h(o){const i=`https://pixabay.com/api/?${new URLSearchParams({key:"43050559-0509edef54e5bc117deb7e6a8",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(i).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const g=document.querySelector(".gallery");function y(o){if(o.length==0)c.error({message:"Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const s=o.map(t=>`<li class="photo-list-item">
        <a class="photos-list-link" href="${t.largeImageURL}">
        <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
        </a>
        <ul class="container">
        <li class="item-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
        <li class="item-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
        <li class="item-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
        <li class="item-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
        </ul>
        </li>`).join("");g.insertAdjacentHTML("beforeend",s),new p(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}}const L=document.querySelector(".gallery");let n;const l=document.querySelector("input"),u=document.querySelector("form"),m=document.querySelector(".loader");d();function b(){m.classList.remove("hidden")}function d(){m.classList.add("hidden")}l.addEventListener("input",o=>{o.preventDefault(),n=l.value.trim()});u.addEventListener("submit",o=>{o.preventDefault(),b(),L.innerHTML="",n===""&&c.error({color:"red",message:" Please fill in the field for search",position:"topRight"}),n&&h(n).then(s=>y(s.hits)).catch(s=>{console.log(s),c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}).finally(()=>d()),u.reset()});
//# sourceMappingURL=commonHelpers.js.map
